server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现和路由功能
          lower-case-service-id: true # 使用小写服务ID
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: user-label
          uri: lb://user-label
          predicates:
            - Path=/user-label/**
        - id: message
          uri: lb://message
          predicates:
            - Path=/message/**